import openpyxl
from openpyxl import Workbook

def generate_sample_xlsx(path="app/pipeline/sample_access_log.xlsx"):
    wb = Workbook()
    ws = wb.active
    ws.title = "Access Log"

    # 5 scaffold/header rows to strip
    ws.append(["REPORT GENERATED BY: Security System v2.1"])
    ws.append(["LOCATION: Sentry HQ"])
    ws.append(["DATE RANGE: 2026-01-01 to 2026-01-31"])
    ws.append(["CONFIDENTIAL - DO NOT DISTRIBUTE"])
    ws.append([""])  # empty row

    # Real header
    ws.append(["badge_code", "person_id", "event_ts", "direction", "location"])

    # Clean rows
    ws.append(["B001", "P001", "2026-01-15 09:00:00", "IN", "Main Gate"])
    ws.append(["B001", "P001", "2026-01-15 17:00:00", "OUT", "Main Gate"])
    ws.append(["B002", "P002", "2026-01-15 09:05:00", "IN", "Main Gate"])

    # Double-tap swipe (duplicate within 5 seconds)
    ws.append(["B002", "P002", "2026-01-15 09:05:03", "IN", "Main Gate"])

    # -- sentinels (should become NULL)
    ws.append(["--", "P003", "2026-01-15 09:10:00", "IN", "--"])

    # Formula injection attempt
    ws.append(["=CMD|' /C calc'!A0", "P004", "2026-01-15 09:15:00", "IN", "Main Gate"])

    # Bad timestamp
    ws.append(["B005", "P005", "not-a-date", "IN", "Main Gate"])

    # Missing direction
    ws.append(["B006", "P006", "2026-01-15 09:20:00", "", "Main Gate"])

    # Valid rows
    ws.append(["b003 ", "P007", "2026-01-15 09:25:00", "OUT", "Side Gate"])
    ws.append(["B004", "P008", "2026-01-15 09:30:00", "IN", "Main Gate"])
    ws.append(["B002", "P002", "2026-01-15 17:05:00", "OUT", "Main Gate"])

    wb.save(path)
    print(f"Sample xlsx generated at {path}")

if __name__ == "__main__":
    generate_sample_xlsx()
    