"""create github data schema

Revision ID: 0aa1b8a64c32
Revises: 7a56c52248d9
Create Date: 2026-06-17 11:36:20.284736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa1b8a64c32'
down_revision: Union[str, Sequence[str], None] = '7a56c52248d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_check_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('conclusion', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_check_run_sha'), 'ci_check_run', ['sha'], unique=False)
    op.create_table('deployment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('deployer_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_sha'), 'deployment', ['sha'], unique=False)
    op.create_table('git_file_change',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_git_file_change_sha'), 'git_file_change', ['sha'], unique=False)
    op.create_table('pull_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('merged', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pr_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pr_review')
    op.drop_table('pull_request')
    op.drop_index(op.f('ix_git_file_change_sha'), table_name='git_file_change')
    op.drop_table('git_file_change')
    op.drop_index(op.f('ix_deployment_sha'), table_name='deployment')
    op.drop_table('deployment')
    op.drop_index(op.f('ix_ci_check_run_sha'), table_name='ci_check_run')
    op.drop_table('ci_check_run')
    # ### end Alembic commands ###
