"""create github data schema

Revision ID: 7a56c52248d9
Revises: d8efadf61cfb
Create Date: 2026-06-17 11:35:42.529121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a56c52248d9'
down_revision: Union[str, Sequence[str], None] = 'd8efadf61cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_allowlist')
    op.drop_index(op.f('ix_dim_person_email'), table_name='dim_person')
    op.drop_table('dim_person')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_person',
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('github_login', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_employee', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('person_id', name=op.f('dim_person_pkey')),
    sa.UniqueConstraint('email', name=op.f('uq_dim_person_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_dim_person_email'), 'dim_person', ['email'], unique=False)
    op.create_table('person_allowlist',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('account_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['dim_person.person_id'], name=op.f('person_allowlist_person_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('person_allowlist_pkey')),
    sa.UniqueConstraint('identifier', name=op.f('uq_person_allowlist_identifier'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
