"""create access event tables

Revision ID: 94ef18da50ea
Revises: b0242b689ea2
Create Date: 2026-06-16 10:17:28.622327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94ef18da50ea'
down_revision: Union[str, Sequence[str], None] = 'b0242b689ea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fact_access_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('event_ts', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('raw_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'event_ts', 'direction', name='uq_fact_access_event')
    )
    op.create_index('ix_fact_access_event_person_ts', 'fact_access_event', ['person_id', 'event_ts'], unique=False)
    op.create_table('raw_access_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_access_events')
    op.drop_index('ix_fact_access_event_person_ts', table_name='fact_access_event')
    op.drop_table('fact_access_event')
    # ### end Alembic commands ###
